[build]
builder = "NIXPACKS"
buildCommand = "npm install -g pnpm@10.6.3 && pnpm install --no-frozen-lockfile && pnpm build"

[deploy]
numReplicas = 1
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
startCommand = "pnpm start"

[service]
name = "utility-service"
internalPort = 8080
healthcheckPath = "/health"

[variables]
PORT = 8080
NODE_ENV = "production"
ANTHROPIC_API_KEY="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"
GITHUB_TOKEN="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"
GITHUB_OWNER="blooming-generation"
GITHUB_REPO="agent-base"
FIRECRAWL_API_KEY="fc-663f2fffacec43f68745b8a5e8a46f99"
SERPAPI_API_KEY="099ed17faf02bc2555c3d2e2811e4812f966cd04198b105844ee1caff320f341"
GOOGLE_CLIENT_ID="436470577293-5akhvrp7rpuk55uko744tok9d7keg8nh.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET="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"
XATA_API_KEY="xau_8p858McJOjmGi8OGvSnVoUYV2MV9zErH0"
XATA_BRANCH="main"
XATA_WORKSPACE_SLUG="KevinLourd-s-workspace"
XATA_DATABASE_ID="KevinLourd-s-workspace-g75e28"
