[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"

[deploy]
numReplicas = 1
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[service]
name = "web-gateway-service"
# Use Railway's standard port
internalPort = 8080
healthcheckPath = "/health"
domains = ["gateway.agent-base.ai"]

[variables]
PORT = "8080"
NODE_ENV = "production"
ALLOWED_ORIGINS = "https://www.agent-base.ai,https://agent-base.ai"
AUTH_SERVICE_URL = "http://auth-service.railway.internal:8080"
DB_SERVICE_URL = "http://database-service.railway.internal:8080"
MODEL_SERVICE_URL = "http://model-service.railway.internal:8080"
API_GATEWAY_SERVICE_URL = "http://api-gateway-service.railway.internal:8080"
KEYS_SERVICE_URL = "http://key-service.railway.internal:8080"
PAYMENT_SERVICE_URL = "http://payment-service.railway.internal:8080"
LOGGING_SERVICE_URL="http://logging-service.railway.internal:8080"

WEB_GATEWAY_API_KEY = "g4t3way-k3y-e5e821f89a2d4c3b" 