[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"

[deploy]
numReplicas = 1
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[service]
name = "web-gateway-service"
# Use Railway's standard port
internalPort = 8080
healthcheckPath = "/health"
domains = ["gateway.agent-base.ai"]

[variables]
# Set PORT env variable to match Railway's standard port
PORT = "8080"
NODE_ENV = "production"
ALLOWED_ORIGINS = "https://www.agent-base.ai,https://agent-base.ai" 