packages:
  # - apps/logging-service
  - apps/secret-service
  - apps/agent-service
  - apps/database-service
  - apps/utility-tool-service
  - apps/api-gateway-service
  - apps/user-service
  # - apps/web-oauth-service
  - apps/web-gateway-service
  - apps/payment-service
  - apps/key-service
  # - apps/webhook-gateway-service
  # - apps/agent-base-app
  - apps/whatsapp-service
  - apps/tool-auth-service
  - apps/dashboard-service
  - packages/**
  - tooling/*

