packages:
  - apps/logging-service
  - apps/secret-service
  - apps/agent-service
  - apps/database-service
  # - apps/tool-auth-service
  - apps/utility-tool-service
  - apps/api-gateway-service
  - apps/web-oauth-service
  - apps/web-gateway-service
  - apps/payment-service
  - apps/key-service
  - apps/webhook-gateway-service
  - packages/**
  - tooling/*
  - company-flow-web
  - webhook-tool-backend
  - api-tool-backend
