packages:
  - apps/logging-service
  - apps/secret-service
  - apps/agent-service
  - apps/database-service
  - apps/tool-auth-service
  - apps/utility-tool-service
  - apps/api-gateway-service
  - apps/auth-service
  - apps/web-gateway-service
  - apps/payment-service
  - apps/key-service
  - apps/webhook-gateway-service
  - packages/**
  - tooling/*
