[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"

[deploy]
numReplicas = 1
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[service]
name = "database-service"
internalPort = 3006
healthcheckPath = "/health"

[variables]
PORT = "3006"
NODE_ENV = "production"

# Railway will automatically inject the Postgres connection variables
# when the Postgres plugin is added to the project, with variables like:
# PGDATABASE, PGHOST, PGUSER, PGPASSWORD, PGPORT, DATABASE_URL 