[build]
builder = "NIXPACKS"
buildCommand = "npm install -g pnpm@10.6.3 && pnpm install --no-frozen-lockfile && pnpm build"

[deploy]
numReplicas = 1
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
startCommand = "pnpm start"

[service]
name = "model-service"
internalPort = 8080
healthcheckPath = "/health"

[variables]
PORT = "8080"
NODE_ENV = "production"
ANTHROPIC_API_KEY=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
UTILITY_SERVICE_URL=http://utility-service.railway.internal:3008