[build]
builder = "NIXPACKS"
buildCommand = "npm run railway:build"

[deploy]
numReplicas = 1
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5
startCommand = "pnpm start"

[service]
name = "model-service"
internalPort = 3001
healthcheckPath = "/health"

[variables]
PORT = "3001"
NODE_ENV = "production"
NIXPACKS_PKGS = "nodejs" 