[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"

[deploy]
numReplicas = 1
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[service]
name = "model-service"
internalPort = 3001
healthcheckPath = "/health"

[variables]
PORT = "3001"
NODE_ENV = "production" 