[build]
builder = "NIXPACKS"
buildCommand = "pnpm install && pnpm run build"

[deploy]
numReplicas = 1
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[service]
name = "api-gateway-service"
internalPort = 8080
healthcheckPath = "/health"
domains = ["api.helloworld.example.com"]

[variables]
PORT = "8080"
NODE_ENV = "production"
MODEL_SERVICE_URL = "http://model-service.railway.internal:8080"
UTILITY_SERVICE_URL = "http://utility-service.railway.internal:8080"
KEY_SERVICE_URL = "http://key-service.railway.internal:8080"
LOGGING_SERVICE_URL="http://logging-service.railway.internal:8080"
