[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"

[deploy]
numReplicas = 1
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[service]
name = "auth-service"
internalPort = 8080
healthcheckPath = "/health"
domains = ["auth.helloworld.example.com"]

[variables]
PORT = "8080"
NODE_ENV = "production"
JWT_SECRET = "${JWT_SECRET}" 