[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"

[deploy]
numReplicas = 1
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[service]
name = "auth-service"
internalPort = 8080
healthcheckPath = "/health"
domains = ["auth.helloworld.example.com"]

[variables]
PORT = "8080"
NODE_ENV = "production"
JWT_SECRET = "helloworld_jwt_secret_key"
SESSION_SECRET = "helloworld_session_secret_key"
# Client App
CLIENT_APP_URL = "https://agent-base.ai"
# Service URLs
AUTH_SERVICE_URL = "http://auth-service.railway.internal:8080"
WEB_GATEWAY_URL = "http://web-gateway-service.railway.internal:8080"
# Google OAuth Configuration
GOOGLE_CLIENT_ID = "436470577293-5akhvrp7rpuk55uko744tok9d7keg8nh.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = "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"
GOOGLE_REDIRECT_URI = "https://gateway.agent-base.ai/oauth/google/callback" 