[phases.setup]
cmds = [
  "corepack enable",
  "corepack prepare pnpm@10.6.3 --activate"
]

[phases.install]
cmds = [
  "pnpm install --no-frozen-lockfile"
]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "pnpm start" 