[variables]
NODE_VERSION = "18.x"

[phases.setup]
aptPkgs = ["nodejs"]
cmds = [
  "npm install -g corepack",
  "corepack enable",
  "corepack prepare pnpm@10.6.2 --activate"
]

[phases.install]
cmds = [
  "pnpm install --no-frozen-lockfile"
]

[phases.build]
cmds = ["pnpm build"]

[start]
cmd = "node dist/index.js" 