[build]
builder = "NIXPACKS"
buildCommand = "npm install && npm run build"

[deploy]
numReplicas = 1
healthcheckPath = "/health"
healthcheckTimeout = 10
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[service]
name = "key-service"
internalPort = 8080
healthcheckPath = "/health"

[variables]
PORT = "8080"
NODE_ENV = "production"
DB_SERVICE_URL="http://database-service.railway.internal:8080"